'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Check, Share2, Download, Lightbulb, GitBranch, Sparkles, Printer } from 'lucide-react';
import { Tool, ToolResult } from '@/lib/tools';
import { Button } from '@/components/ui/Button';
import { ConfidenceBadge } from './ConfidenceBadge';
import { ToolOutputGrid } from './ToolOutput';
import { ToolChart } from './ToolChart';

interface ToolResultDisplayProps {
  tool: Tool;
  result: ToolResult;
  inputs: Record<string, string | number>;
  onEnhance?: () => void;
  isEnhancing?: boolean;
}

export function ToolResultDisplay({ tool, result, inputs, onEnhance, isEnhancing }: ToolResultDisplayProps) {
  const [shareCopied, setShareCopied] = useState(false);

  const handleShare = () => {
    const params = new URLSearchParams();
    Object.entries(inputs).forEach(([key, value]) => {
      if (value !== '' && value !== undefined) {
        params.set(key, String(value));
      }
    });
    const url = `${window.location.origin}/tools/${tool.slug}?${params.toString()}`;
    navigator.clipboard.writeText(url);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  };

  const handleDownload = () => {
    const exportData = {
      tool: tool.name,
      generatedAt: new Date().toISOString(),
      inputs,
      confidence: result.confidence,
      confidenceLevel: result.confidenceLevel,
      summary: result.summary,
      outputs: result.outputs.map(o => ({ label: o.label, value: o.value })),
      recommendations: result.recommendations,
    };
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tool.slug}-results.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  // Check if enhancement is available (has long text output)
  const canEnhance = result.outputs.some(o => o.format === 'text' && String(o.value).length > 50);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6 print:space-y-4"
    >
      {/* Confidence & Actions */}
      <div className="flex items-center justify-between print:hidden">
        <ConfidenceBadge
          confidence={result.confidence}
          level={result.confidenceLevel}
        />
        <div className="flex gap-2">
          {canEnhance && onEnhance && (
            <Button 
              variant="primary" 
              size="sm" 
              onClick={onEnhance} 
              disabled={isEnhancing}
              className="bg-violet-500/20 text-violet-300 hover:bg-violet-500/30 border-violet-500/50"
            >
              {isEnhancing ? (
                 <motion.div
                   className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full mr-2"
                   animate={{ rotate: 360 }}
                   transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                 />
              ) : (
                <Sparkles className="w-4 h-4 mr-2" />
              )}
              {isEnhancing ? 'Enhancing...' : 'Enhance with AI'}
            </Button>
          )}
          <Button variant="ghost" size="sm" onClick={handlePrint} aria-label="Print report">
            <Printer className="w-4 h-4" aria-hidden="true" />
          </Button>
          <Button variant="ghost" size="sm" onClick={handleShare} aria-label="Share results link">
            {shareCopied ? (
              <Check className="w-4 h-4 text-emerald-400" aria-hidden="true" />
            ) : (
              <Share2 className="w-4 h-4" aria-hidden="true" />
            )}
          </Button>
          <Button variant="ghost" size="sm" onClick={handleDownload} aria-label="Download JSON">
            <Download className="w-4 h-4" aria-hidden="true" />
          </Button>
        </div>
      </div>

      {/* Print Header (Visible only in print) */}
      <div className="hidden print:block mb-6 border-b border-slate-200 pb-4">
        <h1 className="text-2xl font-bold text-slate-900">{tool.name} Report</h1>
        <p className="text-slate-500 text-sm">Generated by BrainStack Studio on {new Date().toLocaleDateString()}</p>
      </div>

      {/* Summary */}
      <div className="p-4 rounded-lg bg-slate-800/50 border border-slate-700 print:bg-white print:border-slate-200 print:p-0" role="status" aria-live="polite">
        <p className="text-slate-300 print:text-slate-700 leading-relaxed">{result.summary}</p>
      </div>

      {/* Outputs Grid */}
      <div className="print:block">
        <ToolOutputGrid outputs={result.outputs} />
      </div>

      {/* Chart */}
      {result.chart && (
        <div className="p-6 rounded-xl bg-slate-900/50 border border-slate-800 print:border-slate-200 print:bg-white print:break-inside-avoid">
          <h4 className="text-sm font-medium text-slate-400 mb-4 print:text-slate-600">Projection</h4>
          <ToolChart data={result.chart} height={220} />
        </div>
      )}

      {/* Recommendations */}
      {result.recommendations.length > 0 && (
        <div className="p-6 rounded-xl bg-slate-900/50 border border-slate-800 print:border-slate-200 print:bg-white print:break-inside-avoid">
          <h4 className="text-sm font-medium text-slate-400 mb-3 flex items-center gap-2 print:text-slate-900">
            <Lightbulb className="w-4 h-4 text-amber-400 print:text-amber-600" aria-hidden="true" />
            Recommendations
          </h4>
          <ul className="space-y-2">
            {result.recommendations.map((rec, i) => (
              <li key={i} className="flex gap-2 text-sm text-slate-300 print:text-slate-700">
                <span className="text-cyan-400 print:text-cyan-600">•</span>
                {rec}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Decision Trail */}
      {result.decisionTrail.length > 0 && (
        <details className="group print:hidden">
          <summary className="flex items-center gap-2 text-sm text-slate-500 cursor-pointer hover:text-slate-400">
            <GitBranch className="w-4 h-4" aria-hidden="true" />
            Decision Trail
            <span className="text-xs opacity-50">(click to expand)</span>
          </summary>
          <div className="mt-3 p-4 rounded-lg bg-slate-900/30 border border-slate-800">
            <ol className="space-y-1.5 text-xs text-slate-500">
              {result.decisionTrail.map((step, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-slate-600 font-mono">{i + 1}.</span>
                  {step}
                </li>
              ))}
            </ol>
          </div>
        </details>
      )}
    </motion.div>
  );
}
